import "./globals.css";
import type { Metadata } from "next";
import { Special_Elite } from "next/font/google";
import Providers from "./components/Providers";

const specialElite = Special_Elite({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${specialElite.className} container mx-auto max-w-5xl px-4 bg-gradient-to-r from-pink-400 via-pink-300 to-pink-400 text-slate-700 selection:bg-pink-300 selection:text-slate-100`}
      >
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
