import "./globals.css";
import type { Metadata } from "next";
import { Special_Elite } from "next/font/google";
import Providers from "./components/Providers";

const specialElite = Special_Elite({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${specialElite.className} container mx-auto max-w-5xl px-4 bg-slate-100 text-slate-700 selection:bg-pink-300 selection:text-slate-100 dark:bg-pink-300 dark:text-slate-700 dark:selection:slate-100 dark:selection:bg-pink-400 `}
      >
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
